//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPK_Test.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visits
    {
        public System.Guid VisitID { get; set; }
        public Nullable<System.DateTime> DateVisit { get; set; }
        public string Diagnose { get; set; }
        public Nullable<System.Guid> PatientID { get; set; }
    
        public virtual Patients Patients { get; set; }
    }
}
